interface MatchType {
    winConditions?: string
    description: string
  }
  
  export const basicControls = {
    "In the Ring": [
      "Control Superstar - Directional Buttons or Left Analog Stick",
      "Run - Triangle",
      "Initiate Grapple - Circle + Directional Button",
      "Power Grapple - Circle + Up",
      "Submission Grapple - Circle + Down",
      "Signature Grapple - Circle + Left",
      "Quick Grapple - Circle + Right",
      "Perform Grapple Move - Circle + Directional",
      "Perform Strike Move - X + Directional",
      "Striking Attack - X",
      "Irish Whip - Circle",
      "Counter Striking Attack - L2",
      "Counter Grapple Attack - R2",
      "Counter Smackdown! Move - L2 + R2",
      "Taunt - Right Analog Stick",
      "Pin (adversary on mat) - Circle + Down",
      "Layeth the Smackdown! - L1",
      "Second Finisher - L1 + Directional",
      "Pick up weapon or object - Square",
      "Action - Triangle + Directional toward object",
      "Change Focus - R1",
      "Pause - Start",
    ],
    "Facing Adversary": [
      "Irish Whip - Circle",
      "Striking Attacks - X / X + Directional",
      "Grapple Attacks (min. damage) - Circle / Circle + Directional",
    ],
    "Behind Adversary": [
      "Irish Whip - Circle",
      "Fake Irish Whip - Circle, Square",
      "Rear Grapple Attacks - Circle / Circle + Directional",
    ],
    "Adversary on Mat": [
      "Lift adversary into Grapple - Circle",
      "Pin adversary - Circle + Down",
      "Break your own pin - Square",
      "Upper body grapple attacks - Circle + Directional",
      "Lower body grapple attacks - Circle + Directional",
      "Lift adversary (facing adversary's back) - Circle + Circle",
      "Striking Attacks - X / X + Left or Right / X + Down or Up",
      "Drag Adversary - Hold Circle",
      "Running Ground Strike - Triangle + Circle + X",
    ],
    "Turnbuckle/Ropes": [
      "Enter/Exit Ring - Square + Directional toward ropes",
      "Climb Turnbuckle - Triangle + Directional toward corner",
      "Dismount Turnbuckle - Square",
      "Rope Attack (adversary on ropes) - Circle + Directional",
      "Irish Whip to Ropes - Circle + Directional toward ropes",
      "Adversary's Back to Turnbuckle - Circle + Up, Down, Left, or Right",
      "Adversary Facing Turnbuckle - Circle + Up, Down, Left, or Right",
      "Adversary Sitting on Turnbuckle - Circle + Up, Down, Left, or Right",
      "Remove Turnbuckle - Square + Directional toward turnbuckle",
      "Tag Team Turnbuckle Attacks - Circle + Up, Down, Left, or Right",
    ],
    "Running Maneuvers": [
      "Running Grapple (toward adversary's face/back) - Triangle, Circle + Directional",
      "Running Strike - Triangle, X + Directional",
      "Counter Irish Whip - R2 while at ropes",
    ],
    "High-Flying Maneuvers": ["Diving Attacks - X / X + Left, Right, Up, or Down", "Counter High-Flying Moves - L2"],
    "Weapon Attacks": [
      "Get weapon from under apron - Circle + Directional toward center of apron",
      "Pick Up/Drop Weapon - Square",
      "Weapon Grapple - X + Up or Down",
      "Weapon Strike - X + Left or Right",
      "Running Weapon Attack - Triangle + Directional toward adversary, strike adversary w/ X button",
      "Weapon Special - L1 while holding a chair",
      "Throw Weapon - Circle",
    ],
    "Tag Team Maneuvers": [
      "Get on outside of apron - Square + Directional toward corner",
      "Call for Tag on apron - Square",
      "Tag Partner - Square + Directional toward partner",
      "Call in Partner - Right Analog Stick",
    ],
    "Ladder Match Maneuvers": [
      "Pick up Ladder - Square (near ladder)",
      "Stand Ladder - Square (while holding ladder)",
      "Place Ladder in Turnbuckle - Square + Directional toward turnbuckle",
      "Climb Ladder - Square + Directional",
      "Diving Attack - X (while standing on ladder)",
      "Reach for Belt - Circle (while standing on ladder)",
      "Jump for Belt - Circle + Directional (while standing on ladder)",
      "Climb Down Ladder - Square (while standing on ladder)",
      "Knock Ladder Over - Square (standing near ladder)",
    ],
    "Table Match Maneuvers": [
      "Pick up Table - Square (near table)",
      "Stand Table - Square (while holding table)",
      "Place Table in Turnbuckle - Square + Directional toward turnbuckle",
      "Throw Adversary onto Table - Hold table and press Up or Down + X",
      "Grapple Adversary through Table - Circle (standing on table w/adversary)",
      "Climb onto Table - Triangle (run toward table)",
      "Dive from Table Attack - X (while standing on table w/o adversary)",
      "Recover - Directional buttons (repeatedly)",
    ],
    "Cage Match/ Hell in a Cell Maneuvers": [
      "Climb Cage - Square + Directional (toward cage)",
      "Climb Cell - Triangle",
      "Dive from Cage Attack - X (on top of cage)",
      "Push adversary off of Cage (Hell in a Cell) - Circle (near edge of top of cage)",
      "Open cage door - Triangle + Directional button",
    ],
    "Bra-and-Panties Match Maneuvers": ["Remove garments - Circle + Down (from behind, adversary groggy, or on ground)"],
    "Special Referee Maneuvers": [
      "Count Pin - Square (during pin fall)",
      "Count Ring Out - Square (during Ring Out)",
      "Count Disqualification - Square (during weapon attack)",
      "Count Give Up - Square (during submission)",
    ],
    "Elimination Chamber Maneuvers": [
      "Climb Chamber Wall - Square + Directional toward wall",
      "Climb on top of Chamber - Square + Directional while on turnbuckle",
      "Perform Diving Attack - X while hanging on chamber wall",
      "Pull down Adversary - Circle while adversary hangs on wall",
    ],
  }
  
  export const matchTypes: Record<string, MatchType> = {
    "Tag Match": {
      winConditions: "Pin Fall, Submission, or Disqualification",
      description: "Two Teams of two take on one another for the glory!",
    },
    "Handicap Match": {
      winConditions: "Pin Fall, Submission, or Disqualification",
      description: "One Superstar must face two, or sometimes even three opponents at once! Scary!",
    },
    "Hardcore Match": { description: "No rules, no disqualifications! Use any weapon you can find!" },
    "Royal Rumble": {
      description: "30 Superstars enter, one wins! Throw your opponents over the top rope to eliminate them.",
    },
    "Survival Match": { description: "Team vs Team elimination match. Last team standing wins!" },
    "Three Stages of Hell": { description: "Best 2 out of 3 matches, each with different rules!" },
    "Bra & Panties Match": { description: "Strip your opponent to win!" },
    "Cage Match": { description: "Escape the cage or make your opponent submit to win!" },
    "Elimination Chamber Match": { description: "6 Superstars, 4 in pods. Last one standing wins!" },
    "Elimination Tag Match": { description: "Tag team match where members must be eliminated to win!" },
    "First Blood Match": { description: "Make your opponent bleed to win!" },
    "Hell in a Cell Match": { description: "Locked inside a massive steel structure. No escape!" },
    "Ironman Match": { description: "Most falls in the time limit wins!" },
    "Ladder Match": { description: "Climb the ladder to grab the prize hanging above!" },
    "Last Man Standing Match": { description: "Knock out your opponent for a 10 count to win!" },
    "Lumber Jack Match": { description: "Ring surrounded by other Superstars who throw you back in!" },
    "Slobber Knocker Match": { description: "Endless opponents until you can't continue!" },
    "Special Referee Match": { description: "A special guest referee controls the match!" },
    "Submission Match": { description: "Victory only by submission!" },
    "Table Match": { description: "Put your opponent through a table to win!" },
  }
  